application:
  openapi:
    title: ${OPENAPI_TITLE}
    version: ${OPENAPI_VERSION}
    description: ${OPENAPI_DESCRIPTION}
    name: ${OPENAPI_NAME}
    email: ${OPENAPI_EMAIL}

  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION_MS}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION_MS}
      remember-me-expiration: ${JWT_REMEMBER_ME_EXPIRATION_MS}

    cookies:
      secure: ${COOKIES_SECURE}

  super_admin:
    first_name: ${SUPER_ADMIN_FIRST_NAME}
    last_name: ${SUPER_ADMIN_LAST_NAME}
    email: ${SUPER_ADMIN_EMAIL}
    password: ${SUPER_ADMIN_PASSWORD}

  frontend:
    url: ${FRONTEND_URL}

  token:
    pepper: ${TOKEN_PEPPER} # used to sign the refresh-token 'use SHA256 64-bit key for this'

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    show-sql: false

    properties:
      hibernate:
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true

  mail:
    host: smtp.gmail.com        # or any other smtp server of your choice
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

imagekit:
  private-key: ${IMAGEKIT_PRIVATE_KEY}