spring:
  application:
    name: backend

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev

server:
  port: 8080
  servlet:
    context-path: /api