--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accessories; Type: TABLE; Schema: public; Owner: abdo
--

CREATE TABLE public.accessories (
                                    price numeric(10,2) NOT NULL,
                                    stock integer NOT NULL,
                                    version integer NOT NULL,
                                    category_id bigint NOT NULL,
                                    created_at timestamp(6) without time zone NOT NULL,
                                    id bigint NOT NULL,
                                    updated_at timestamp(6) without time zone NOT NULL,
                                    product_code character varying(10) NOT NULL,
                                    title character varying(150) NOT NULL,
                                    description character varying(1000) NOT NULL,
                                    image_url character varying(500)
);



--
-- Name: accessories_id_seq; Type: SEQUENCE; Schema: public; Owner: abdo
--

ALTER TABLE public.accessories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accessories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: accessory_categories; Type: TABLE; Schema: public; Owner: abdo
--

CREATE TABLE public.accessory_categories (
                                             version integer NOT NULL,
                                             created_at timestamp(6) without time zone NOT NULL,
                                             id bigint NOT NULL,
                                             updated_at timestamp(6) without time zone NOT NULL,
                                             name character varying(50) NOT NULL,
                                             description character varying(500) NOT NULL,
                                             image_url character varying(500) NOT NULL
);



--
-- Name: accessory_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: abdo
--

ALTER TABLE public.accessory_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accessory_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: email_verifications; Type: TABLE; Schema: public; Owner: abdo
--

CREATE TABLE public.email_verifications (
                                            verified boolean NOT NULL,
                                            expires_at timestamp(6) without time zone NOT NULL,
                                            id bigint NOT NULL,
                                            token character varying(500) NOT NULL,
                                            user_id character varying(255) NOT NULL
);



--
-- Name: email_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: abdo
--

ALTER TABLE public.email_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.email_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: abdo
--

CREATE TABLE public.refresh_tokens (
                                       remember_me boolean NOT NULL,
                                       valid boolean NOT NULL,
                                       expires_at timestamp(6) without time zone NOT NULL,
                                       id bigint NOT NULL,
                                       token character varying(500) NOT NULL,
                                       user_id character varying(255) NOT NULL
);



--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: abdo
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: reset_passwords; Type: TABLE; Schema: public; Owner: abdo
--

CREATE TABLE public.reset_passwords (
                                        verified boolean NOT NULL,
                                        expires_at timestamp(6) without time zone NOT NULL,
                                        id bigint NOT NULL,
                                        token character varying(500) NOT NULL,
                                        user_id character varying(255) NOT NULL
);



--
-- Name: reset_passwords_id_seq; Type: SEQUENCE; Schema: public; Owner: abdo
--

ALTER TABLE public.reset_passwords ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.reset_passwords_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users; Type: TABLE; Schema: public; Owner: abdo
--

CREATE TABLE public.users (
                              deleted boolean NOT NULL,
                              enabled boolean NOT NULL,
                              version integer NOT NULL,
                              created_at timestamp(6) without time zone NOT NULL,
                              deleted_at timestamp(6) without time zone,
                              updated_at timestamp(6) without time zone NOT NULL,
                              email character varying(150) NOT NULL,
                              first_name character varying(150) NOT NULL,
                              last_name character varying(150),
                              password character varying(250) NOT NULL,
                              id character varying(255) NOT NULL
);



--
-- Name: users_role; Type: TABLE; Schema: public; Owner: abdo
--

CREATE TABLE public.users_role (
                                   id bigint NOT NULL,
                                   created_at timestamp(6) without time zone NOT NULL,
                                   deleted boolean NOT NULL,
                                   deleted_at timestamp(6) without time zone,
                                   name character varying(50) NOT NULL,
                                   updated_at timestamp(6) without time zone NOT NULL,
                                   version integer NOT NULL
);



--
-- Name: users_role_id_seq; Type: SEQUENCE; Schema: public; Owner: abdo
--

ALTER TABLE public.users_role ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
    );


--
-- Name: users_roles_mapping; Type: TABLE; Schema: public; Owner: abdo
--

CREATE TABLE public.users_roles_mapping (
                                            role_id bigint NOT NULL,
                                            user_id character varying(255) NOT NULL
);



--
-- Name: accessories accessories_pkey; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.accessories
    ADD CONSTRAINT accessories_pkey PRIMARY KEY (id);


--
-- Name: accessories accessories_product_code_key; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.accessories
    ADD CONSTRAINT accessories_product_code_key UNIQUE (product_code);


--
-- Name: accessory_categories accessory_categories_name_key; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.accessory_categories
    ADD CONSTRAINT accessory_categories_name_key UNIQUE (name);


--
-- Name: accessory_categories accessory_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.accessory_categories
    ADD CONSTRAINT accessory_categories_pkey PRIMARY KEY (id);


--
-- Name: email_verifications email_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.email_verifications
    ADD CONSTRAINT email_verifications_pkey PRIMARY KEY (id);


--
-- Name: email_verifications email_verifications_token_key; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.email_verifications
    ADD CONSTRAINT email_verifications_token_key UNIQUE (token);


--
-- Name: email_verifications email_verifications_user_id_key; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.email_verifications
    ADD CONSTRAINT email_verifications_user_id_key UNIQUE (user_id);


--
-- Name: users idx_user_email; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT idx_user_email UNIQUE (email);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_token_key UNIQUE (token);


--
-- Name: reset_passwords reset_passwords_pkey; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.reset_passwords
    ADD CONSTRAINT reset_passwords_pkey PRIMARY KEY (id);


--
-- Name: reset_passwords reset_passwords_token_key; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.reset_passwords
    ADD CONSTRAINT reset_passwords_token_key UNIQUE (token);


--
-- Name: reset_passwords reset_passwords_user_id_key; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.reset_passwords
    ADD CONSTRAINT reset_passwords_user_id_key UNIQUE (user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_role users_role_pkey; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.users_role
    ADD CONSTRAINT users_role_pkey PRIMARY KEY (id);


--
-- Name: users_roles_mapping users_roles_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.users_roles_mapping
    ADD CONSTRAINT users_roles_mapping_pkey PRIMARY KEY (role_id, user_id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: users_roles_mapping fk2scg2vrcrmmchspna3a6cs1ji; Type: FK CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.users_roles_mapping
    ADD CONSTRAINT fk2scg2vrcrmmchspna3a6cs1ji FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: users_roles_mapping fk7510y3jf6v2lumos9q7x2214a; Type: FK CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.users_roles_mapping
    ADD CONSTRAINT fk7510y3jf6v2lumos9q7x2214a FOREIGN KEY (role_id) REFERENCES public.users_role(id);


--
-- Name: reset_passwords fkf1pl4tol3esw6ekx4artr05n8; Type: FK CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.reset_passwords
    ADD CONSTRAINT fkf1pl4tol3esw6ekx4artr05n8 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: accessories fkl64oi8eyx4kr8qhx36tv7kpl5; Type: FK CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.accessories
    ADD CONSTRAINT fkl64oi8eyx4kr8qhx36tv7kpl5 FOREIGN KEY (category_id) REFERENCES public.accessory_categories(id);


--
-- Name: email_verifications fkou1xuy3rdeao75p2x1v4v3xs; Type: FK CONSTRAINT; Schema: public; Owner: abdo
--

ALTER TABLE ONLY public.email_verifications
    ADD CONSTRAINT fkou1xuy3rdeao75p2x1v4v3xs FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--