CREATE TABLE carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_cart_user
       FOREIGN KEY (user_id)
           REFERENCES users(id)
);

CREATE TABLE cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT NOT NULL,
    accessory_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,

    CONSTRAINT fk_cart_item_cart
        FOREIGN KEY (cart_id)
            REFERENCES carts(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_cart_item_accessory
        FOREIGN KEY (accessory_id)
            REFERENCES accessories(id),

    CONSTRAINT uk_cart_accessory
        UNIQUE (cart_id, accessory_id),

    CONSTRAINT chk_cart_item_quantity
        CHECK (quantity > 0)
);