ALTER TABLE users
    ADD COLUMN phone_number VARCHAR(50);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id VARCHAR(255) NOT NULL,

    customer_full_name VARCHAR(300) NOT NULL,
    customer_email VARCHAR(150),
    customer_phone_number VARCHAR(50) NOT NULL,

    customer_street VARCHAR(350) NOT NULL,
    customer_city VARCHAR(50) NOT NULL,
    customer_postal_code VARCHAR(50) NOT NULL,
    customer_country VARCHAR(50) NOT NULL,

    payment_method VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    shipping_method VARCHAR(50) NOT NULL,

    notes VARCHAR(1000),

    total_amount NUMERIC(10,2) NOT NULL,

    CONSTRAINT fk_order_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
);


CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id BIGINT NOT NULL,
    accessory_id BIGINT NOT NULL,

    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,

    CONSTRAINT fk_order_item_order
         FOREIGN KEY (order_id)
             REFERENCES orders(id)
             ON DELETE CASCADE,

    CONSTRAINT fk_order_item_accessory
     FOREIGN KEY (accessory_id)
         REFERENCES accessories(id),

    CONSTRAINT uk_order_accessory
        UNIQUE (order_id, accessory_id)
);


ALTER TABLE order_items
    ADD CONSTRAINT chk_order_item_quantity
        CHECK (quantity > 0);

ALTER TABLE order_items
    ADD CONSTRAINT chk_order_item_unit_price
        CHECK (unit_price >= 0);

ALTER TABLE orders
    ADD CONSTRAINT chk_order_total_amount
        CHECK (total_amount >= 0);