CREATE TABLE wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,

    CONSTRAINT uk_wishlist_user
       UNIQUE (user_id),

    CONSTRAINT fk_wishlist_user
       FOREIGN KEY (user_id)
           REFERENCES users(id)
);


CREATE TABLE wishlist_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    wishlist_id BIGINT NOT NULL,
    accessory_id BIGINT NOT NULL,

    created_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_wishlist_item_wishlist
        FOREIGN KEY (wishlist_id)
            REFERENCES wishlists(id)
            ON DELETE CASCADE,

    CONSTRAINT fk_wishlist_item_accessory
        FOREIGN KEY (accessory_id)
            REFERENCES accessories(id),

    CONSTRAINT uk_wishlist_accessory
        UNIQUE (wishlist_id, accessory_id)
);