CREATE TABLE reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id VARCHAR(255) NOT NULL,
    accessory_id BIGINT NOT NULL,

    rating INTEGER NOT NULL,
    comment TEXT,

    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,

    CONSTRAINT fk_review_user
     FOREIGN KEY (user_id)
         REFERENCES users(id),

    CONSTRAINT fk_review_accessory
     FOREIGN KEY (accessory_id)
         REFERENCES accessories(id),

    CONSTRAINT uk_review_user_accessory
     UNIQUE (user_id, accessory_id),

    CONSTRAINT chk_review_rating
     CHECK (rating BETWEEN 1 AND 5)
);